spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: guru # normally would not do this due to security and audit requirements.
    platform: mysql

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create_database.sql

logging:
  level:
    org.springframework.web: DEBUG
    me.cheznic: DEBUG
    org.hibernate: WARN